packages:
  - "libs/*/**"
  - "apps/*/**"

catalog:
  "@chromatic-com/storybook": ^1.5.0
  "@datadog/browser-rum": ^5.28.0
  "@market/icons": ^31.2.0
  "@market/react": ^7.4.0
  "@market/web-components": 6.12.0
  "@nx/nx-linux-x64-gnu": ^18.3.5
  "@rollup/rollup-linux-x64-gnu": ^4.18.0
  "@sentry/node": ^7.116.0
  "@sentry/react": ^7.116.0
  "@square-icons/react": ^13.1.1
  "@square/auth-dev-middleware": ^1.1.0
  "@square/feature-relay-web-sdk": ^2.4.6
  "@square/one-trust": ^1.2.4
  "@square/web-rpc-client": ^2.1.2
  "@squareup/cdp": ^1.0.0
  "@squareup/container-connector": ^1.1.12
  "@squareup/service-container": ^1.12.0
  "@squareup/shared-ui-react": ^1.14.2
  "@squareup/sq-eslint": ^0.1.0
  "@storybook/addon-essentials": ^8.1.5
  "@storybook/addon-interactions": ^8.1.5
  "@storybook/addon-links": ^8.1.5
  "@storybook/preview-api": ^8.1.5
  "@storybook/react-vite": ^8.1.5
  "@storybook/react": ^8.1.5
  "@storybook/test": ^8.1.5
  "@tanstack/eslint-plugin-query": ^5.35.6
  "@tanstack/react-query-devtools": ^5.40.1
  "@tanstack/react-query": ^5.40.1
  "@testing-library/jest-dom": ^6.5.0
  "@testing-library/react": 15.0.6
  "@testing-library/user-event": ^14.4.3
  "@types/compression": ^1.7.5
  "@types/cors": ^2.8.17
  "@types/eslint": ^8.56.10
  "@types/express": ^4.17.21
  "@types/glob": ^8.1.0
  "@types/harmon": ^1.4.4
  "@types/js-cookie": ^3.0.5
  "@types/node": ^20.14.2
  "@types/react-dom": ^18.3.0
  "@types/react": ^18.3.3
  "@types/serve-static": ^1.15.0
  "@types/square-icons__react": ^13.1.0
  "@typescript-eslint/eslint-plugin": ^7.12.0
  "@typescript-eslint/parser": ^7.12.0
  "@vitejs/plugin-react": ^4.3.0
  "@vitest/coverage-v8": ^1.6.0
  "@weebly/magic-mirror": ^1.6.0
  autoprefixer: ^10.4.19
  aws-sdk: ^2.1635.0
  camelcase-keys: ^9.1.3
  compression: ^1.7.4
  cookie: ^1.0.2
  cors: ^2.8.5
  date-fns: ^3.6.0
  decamelize-keys: ^2.0.1
  env-cmd: ^10.1.0
  eslint-config-prettier: ^8.10.0
  eslint-plugin-import: ^2.29.1
  eslint-plugin-jsx-a11y: ^6.10.0
  eslint-plugin-node: ^11.1.0
  eslint-plugin-react-hooks: ^4.6.2
  eslint-plugin-react-refresh: ^0.4.7
  eslint-plugin-react: ^7.34.2
  eslint-plugin-square: ^26.0.0
  eslint-plugin-storybook: ^0.11.1
  eslint-plugin-testing-library: ^6.2.2
  eslint: ^9.10.0
  express: ^4.19.2
  glob: ^11.0.0
  harmon: ^1.4.4
  i18next-icu: ^2.3.0
  i18next-resources-to-backend: ^1.2.1
  i18next: ^23.11.5
  js-cookie: ^3.0.5
  jsdom: ^24.1.0
  long: ^5.2.3
  mime: ^4.0.3
  msw: ^2.3.1
  npm-run-all: ^4.1.5
  nx: ^18.3.5
  postcss: ^8.4.38
  prettier-plugin-organize-imports: ^4.1.0
  prettier: ^3.3.3
  protobufjs: ^7.3.0
  react-dom: ^18.3.1
  react-i18next: ^14.1.2
  react-router: ^7.0.1
  react: ^18.3.1
  serve-static: ^1.15.0
  storybook: ^8.1.5
  tailwindcss: ^3.4.4
  tinycolor2: ^1.6.0
  ts-proto: ^1.181.2
  tsx: ^4.19.2
  typescript: ~5.5.2
  vite-plugin-css-injected-by-js: ^3.5.1
  vite-plugin-dts: ^3.9.1
  vite-plugin-svgr: ^4.2.0
  vite: ^5.2.12
  vitest: ^1.6.0
  xss: ^1.0.15
